spring:
  boot:
    admin:
      monitor:
        default-retries: 3
      ui:
        title: Monitor
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    refresh:
      enable: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://admin:admin@121.40.214.119:8088/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    metadata-map:
      user.name: admin
      user.password: admin
    prefer-ip-address: true
