spring:
  boot:
    admin:
      monitor:
        default-retries: 3
      ui:
        title: Monitor
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    refresh:
      enable: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka/
  instance:
    prefer-ip-address: true
    initial-status: up
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    metadata-map:
      user.name: admin
      user.password: admin
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
